### ISSUE TITLE
Add mini rockets to bus table

### ISSUE THREAD

**Issue by niklasmh** [dotkom/the-notifier-awakens#18]
Just add some SVGs and make it look like this:
![image](https://user-images.githubusercontent.com/8504538/47825567-fa4a8c80-dd72-11e8-996d-d50eb5f9390c.png)

**Comment by monikahm** [comment]
Pushet svg til master først så slettet den, pushet alt til feature/skyrocket

**Comment by niklasmh** [comment]
Closed by #21
